// ============================================================
// state.js — спільний змінний стан та DOM-посилання
// ============================================================

// ---------- Runtime state ----------
const State = {
    hubDatabase:            {},
    uniqueBrandsList:       [],
    currentReportData:      [],
    exportDataArray:        null,
    isExcelArrayExport:     false,
    currentlySelectedBrand: "",
    hubDbTime:              null,
    isSyncBlockCollapsed:   true,
    isRequestBlockCollapsed:true,
    currentSelectedColumns: COLUMN_OPTIONS.map(c => c.key),
    pendingFileData:        null,
    pendingFileName:        null,
    currentChangesHistory:  [],
    changeLogFilter:        "all",
    currentChangeLogPage:   1,
    changeLogPageByFilter:  { all: 1 },
    changeLogPageSize:      20,
    archivedChangesHistory: [],
    searchFilter:           "all",
    activeMainTab:          "brand",
    isSettingsInlineOpen:   false,
    isParametersBlockCollapsed: true,
    parametersChangeLogFilter: "all",
    parametersCurrentChangeLogPage: 1,
    parametersChangeLogPageByFilter: { all: 1 },
    parametersChangesHistory: [],
    parametersArchivedChangesHistory: [],
    parametersChangeLogPageSize: 20,
};

// ---------- DOM references ----------
const Dom = {
    mainContent:            document.getElementById("mainContent"),
    logoHomeBtn:            document.getElementById("logoHomeBtn"),
    openSettingsBtn:        document.getElementById("openSettingsBtn"),
    settingsInlinePanel:    document.getElementById("settingsInlinePanel"),
    enterpriseCopyToggle:   document.getElementById("enterprise-copy-toggle"),
    hotkeysToggle:          document.getElementById("hotkeys-toggle"),
    shortcutsToggle:        document.getElementById("shortcuts-toggle"),
    verificationToggle:     document.getElementById("verification-toggle"),
    enterpriseCopyState:    document.getElementById("enterprise-copy-state"),
    hotkeysState:           document.getElementById("hotkeys-state"),
    shortcutsState:         document.getElementById("shortcuts-state"),
    verificationState:      document.getElementById("verification-state"),
    settingsEnableAllBtn:   document.getElementById("settingsEnableAllBtn"),
    settingsDisableAllBtn:  document.getElementById("settingsDisableAllBtn"),
    brandSearch:            document.getElementById("brandSearch"),
    clearSearch:            document.getElementById("clearSearch"),
    searchFilterSelect:     document.getElementById("searchFilterSelect"),
    uploadFileBtn:          document.getElementById("uploadFileBtn"),
    fileUploadInput:        document.getElementById("fileUploadInput"),
    infoCard:               document.getElementById("infoCard"),
    CampResultsContainer:   document.getElementById("CampResultsContainer"),
    campTableHeadRow:       document.getElementById("campTableHeadRow"),
    campTableBody:          document.getElementById("campTableBody"),
    resultsTitle:           document.getElementById("resultsTitle"),
    historyContainer:       document.getElementById("historyContainer"),
    syncToggleHeader:       document.getElementById("syncToggleHeader"),
    syncCollapseText:       document.getElementById("syncCollapseText"),
    syncStatusBlock:        document.getElementById("syncStatusBlock"),
    syncTimeBlock:          document.getElementById("syncTimeBlock"),
    changeLogFilters:       document.getElementById("changeLogFilters"),
    changeFilterCount:      document.getElementById("changeFilterCount"),
    changeLogPagination:    document.getElementById("changeLogPagination"),
    changeFilterAll:        document.getElementById("changeFilterAll"),
    changeFilterAdded:      document.getElementById("changeFilterAdded"),
    changeFilterModified:   document.getElementById("changeFilterModified"),
    changeFilterRemoved:    document.getElementById("changeFilterRemoved"),
    changeFilterArchived:   document.getElementById("changeFilterArchived"),
    dbChangesLog:           document.getElementById("dbChangesLog"),
    downloadLogBtn:         document.getElementById("downloadLogBtn"),
    requestToggleHeader:    document.getElementById("requestToggleHeader"),
    requestCollapseText:    document.getElementById("requestCollapseText"),
    requestChangesLog:      document.getElementById("requestChangesLog"),
    requestCount:           document.getElementById("requestCount"),
    exportBtn:              document.getElementById("exportBtn"),
    searchSuggestions:      document.getElementById("searchSuggestions"),
    searchHint:             document.getElementById("searchHint"),
    toggleFeedbackBtn:      document.getElementById("toggleFeedbackBtn"),
    feedbackFormBlock:      document.getElementById("feedbackFormBlock"),
    syncRefreshBtn:         document.getElementById("syncRefreshBtn"),
    syncReasonBlock:        document.getElementById("syncReasonBlock"),
    feedbackBrandInput:     document.getElementById("feedbackBrandInput"),
    feedbackBrandSuggestions: document.getElementById("feedbackBrandSuggestions"),
    feedbackCategory:       document.getElementById("feedbackCategory"),
    feedbackMessage:        document.getElementById("feedbackMessage"),
    feedbackManager:        document.getElementById("feedbackManager"),
    submitFeedbackBtn:      document.getElementById("submitFeedbackBtn"),
    columnSelectorBlock:    document.getElementById("columnSelectorBlock"),
    columnSelectorHeader:   document.getElementById("columnSelectorHeader"),
    columnSelectorBody:     document.getElementById("columnSelectorBody"),
    columnCollapseText:     document.getElementById("columnCollapseText"),
    columnSelectorList:     document.getElementById("columnSelectorList"),
    addColumnRuleBtn:       document.getElementById("addColumnRuleBtn"),
    confirmColumnsBtn:      document.getElementById("confirmColumnsBtn"),
    cancelColumnsBtn:       document.getElementById("cancelColumnsBtn"),
    mainTabBrand:           document.getElementById("mainTabBrand"),
    mainTabLogistics:       document.getElementById("mainTabLogistics"),
    mainTabParameters:      document.getElementById("mainTabParameters"),
    tabPanelBrand:          document.getElementById("tabPanelBrand"),
    tabPanelLogistics:      document.getElementById("tabPanelLogistics"),
    tabPanelParameters:     document.getElementById("tabPanelParameters"),
    parametersToggleHeader: document.getElementById("parametersToggleHeader"),
    parametersStatusBlock:  document.getElementById("parametersStatusBlock"),
    parametersTimeBlock:    document.getElementById("parametersTimeBlock"),
    parametersCollapseText: document.getElementById("parametersCollapseText"),
    parametersChangesLog:   document.getElementById("parametersChangesLog"),
    parametersChangeLogFilters: document.getElementById("parametersChangeLogFilters"),
    parametersChangeFilterAll: document.getElementById("parametersChangeFilterAll"),
    parametersChangeFilterAdded: document.getElementById("parametersChangeFilterAdded"),
    parametersChangeFilterModified: document.getElementById("parametersChangeFilterModified"),
    parametersChangeFilterRemoved: document.getElementById("parametersChangeFilterRemoved"),
    parametersChangeFilterArchived: document.getElementById("parametersChangeFilterArchived"),
    parametersFilterCount:  document.getElementById("parametersFilterCount"),
    parametersRefreshBtn:   document.getElementById("parametersRefreshBtn"),
    parametersDownloadLogBtn: document.getElementById("parametersDownloadLogBtn"),
    parametersChangeLogPagination: document.getElementById("parametersChangeLogPagination"),
    parametersReasonBlock:  document.getElementById("parametersReasonBlock"),
};
